<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="Helpers\**" />
	  <Compile Remove="Services\Business\**" />
	  <Compile Remove="temp-key-generator\**" />
	  <Content Remove="Helpers\**" />
	  <Content Remove="Services\Business\**" />
	  <Content Remove="temp-key-generator\**" />
	  <EmbeddedResource Remove="Helpers\**" />
	  <EmbeddedResource Remove="Services\Business\**" />
	  <EmbeddedResource Remove="temp-key-generator\**" />
	  <None Remove="Helpers\**" />
	  <None Remove="Services\Business\**" />
	  <None Remove="temp-key-generator\**" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="ClosedXML" Version="0.102.2" />
		<PackageReference Include="DocumentFormat.OpenXml" Version="2.20.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			
		</PackageReference>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
		<PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.9" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.9" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Data\" />
		<Folder Include="logs\" />
		<Folder Include="Migrations\" />
		<Folder Include="wwwroot\uploads\orders\" />
		<Folder Include="wwwroot\uploads\temp\" />
		
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Franchisee.Web.Tests" />
	</ItemGroup>
</Project>